# Generated by Django 4.0.2 on 2022-02-24 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onl_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL, verbose_name='favourites'),
        ),
    ]
